version: '3.8'

services:
  postgres-saas-db:
    image: postgres:15-alpine
    container_name: drona_os_postgres
    restart: always
    environment:
      POSTGRES_USER: drona_os_admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: drona_os_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_saas_data:/var/lib/postgresql/data

volumes:
  postgres_saas_data: