spring.application.name=Droneos
spring.datasource.url=jdbc:postgresql://localhost:5432/drona_os_dev
spring.datasource.username=drona_os_admin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
# Set to none because Flyway/Liquibase will handle schema creation
spring.jpa.show-sql=true
